function [x,y,q1,q2] = inverseKinEllipse(t,a,b,dir,omega,phi,xc,yc,ox,oy,l1,l2)
%INVERSEKINELLIPSE
%    [X,Y,Q1,Q2] = INVERSEKINELLIPSE(T,A,B,DIR,OMEGA,PHI,XC,YC,OX,OY,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    01-Nov-2019 12:27:28

t2 = dir.*omega.*t;
t3 = sin(t2);
t4 = cos(phi);
t5 = cos(t2);
t6 = sin(phi);
t7 = dir.^2;
t8 = omega.^2;
t9 = a.*t4.*t5;
t14 = b.*t3.*t6;
t10 = ox-t9+t14-xc;
t11 = a.*t5.*t6;
t12 = b.*t3.*t4;
t13 = -oy+t11+t12+yc;
t15 = t10.^2;
t16 = t13.^2;
t17 = t15+t16;
t18 = l1.^2;
t19 = l2.^2;
t20 = t15+t16+t18-t19;
t21 = 1.0./l1;
t22 = 1.0./sqrt(t17);
t23 = b.*dir.*omega.*t4.*t5;
t29 = a.*dir.*omega.*t3.*t6;
t24 = t23-t29;
t25 = a.*dir.*omega.*t3.*t4;
t26 = b.*dir.*omega.*t5.*t6;
t27 = t25+t26;
t28 = t10.*t27.*2.0;
t30 = t13.*t24.*2.0;
t31 = t28+t30;
t42 = real(t11);
t43 = real(t12);
t44 = imag(t14);
t45 = imag(ox);
t46 = imag(xc);
t47 = real(oy);
t48 = real(yc);
t49 = imag(t9);
t32 = t42+t43-t44-t45+t46-t47+t48+t49;
t34 = real(t14);
t35 = imag(oy);
t36 = real(ox);
t37 = imag(yc);
t38 = real(xc);
t39 = real(t9);
t40 = imag(t11);
t41 = imag(t12);
t33 = t34-t35+t36+t37-t38-t39+t40+t41;
t50 = t33.^2;
t51 = 1.0./l1.^2;
t52 = 1.0./t17;
t53 = t20.^2;
t84 = (t51.*t52.*t53)./4.0;
t54 = -t84+1.0;
t55 = 1.0./sqrt(t54);
t56 = 1.0./t17.^(3.0./2.0);
t57 = b.*t3.*t6.*t7.*t8;
t59 = a.*t4.*t5.*t7.*t8;
t58 = t57-t59;
x = [t9+xc-b.*t3.*t6;-a.*dir.*omega.*t3.*t4-b.*dir.*omega.*t5.*t6;t58];
if nargout > 1
    y = [t11+t12+yc;t24;-a.*t5.*t6.*t7.*t8-b.*t3.*t4.*t7.*t8];
end
if nargout > 2
    t60 = t10.*t58.*2.0;
    t61 = a.*t5.*t6.*t7.*t8;
    t62 = b.*t3.*t4.*t7.*t8;
    t63 = t61+t62;
    t64 = t13.*t63.*2.0;
    t65 = t27.^2;
    t66 = t24.^2;
    t96 = t65.*2.0;
    t97 = t66.*2.0;
    t67 = t60+t64-t96-t97;
    t68 = t31.^2;
    t69 = t32.^2;
    t70 = t50+t69;
    t71 = 1.0./t70;
    t72 = 1.0./t33;
    t73 = imag(t23);
    t74 = real(t25);
    t75 = real(t26);
    t76 = imag(t29);
    t77 = t73+t74+t75-t76;
    t78 = real(t23);
    t79 = imag(t25);
    t80 = imag(t26);
    t81 = real(t29);
    t82 = -t78+t79+t80+t81;
    t83 = 1.0./t33.^2;
    t85 = (t21.*t22.*t31)./2.0;
    t86 = t85-(t20.*t21.*t31.*t56)./4.0;
    t87 = t72.*t82;
    t88 = t32.*t77.*t83;
    t89 = t87+t88;
    q1 = [-acos((t20.*t21.*t22)./2.0)+atan2(-oy+yc+a.*t5.*t6+b.*t3.*t4,-ox+t9-t14+xc);t55.*t86+t50.*t71.*t89;-t55.*((t21.*t22.*t67)./2.0+(t21.*t56.*t68)./2.0-(t20.*t21.*t56.*t67)./4.0-1.0./t17.^(5.0./2.0).*t20.*t21.*t68.*(3.0./8.0))-t50.*t71.*(-t72.*(-imag(t57)+imag(t59)+real(t61)+real(t62))+t32.*t83.*(imag(t61)+imag(t62)+real(t57)-real(t59))+t32.*1.0./t33.^3.*t77.^2.*2.0+t77.*t82.*t83.*2.0)+(1.0./t54.^(3.0./2.0).*t86.*((t20.*t31.*t51.*t52)./2.0-(1.0./t17.^2.*t31.*t51.*t53)./4.0))./2.0-t50.*1.0./t70.^2.*t89.*(t33.*t77.*2.0-t32.*t82.*2.0)+t33.*t71.*t77.*t89.*2.0];
end
if nargout > 3
    t90 = 1.0./l2;
    t91 = t15+t16-t18-t19;
    t92 = 1.0./l2.^2;
    t93 = t91.^2;
    t98 = (t51.*t92.*t93)./4.0;
    t94 = -t98+1.0;
    t95 = 1.0./sqrt(t94);
    q2 = [acos((t21.*t90.*t91)./2.0);t21.*t31.*t90.*t95.*(-1.0./2.0);(t21.*t90.*t95.*(t60+t64-t96-t97))./2.0-(1.0./l1.^3.*1.0./l2.^3.*t68.*t91.*1.0./t94.^(3.0./2.0))./8.0];
end
