function out1 = JvEval(in1,l1,l2)
%JVEVAL
%    OUT1 = JVEVAL(IN1,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    23-Jul-2019 15:54:27

q1 = in1(1,:);
q2 = in1(2,:);
t2 = sin(q1);
t3 = cos(q1);
t4 = sin(q2);
t5 = cos(q2);
t6 = l2.*t3.*t5;
out1 = reshape([-l1.*t2-l2.*t2.*t5-l2.*t3.*t4,t6+l1.*t3-l2.*t2.*t4,-l2.*t2.*t5-l2.*t3.*t4,t6-l2.*t2.*t4],[2,2]);
